packages:
  - apps/*
  - packages/*

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1084.0'
  - bullmq@5.80.0
  - icu-minify@4.13.2
  - next-intl-swc-plugin-extractor@4.13.2
  - next-intl@4.13.2
  - prettier@3.9.5
  - use-intl@4.13.2
  - '@eslint/eslintrc@3.3.6'
  - '@eslint/js@9.39.5'
  - eslint@9.39.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - argon2
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
